name: Master

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: bump-version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch

      - id: cache-docker
        uses: actions/cache@v1
        with:
          path: /tmp//tmp/docker-images
          key: /tmp/docker-images-${{ hashFiles('Dockerfile') }}

      - run: docker load -i /tmp//tmp/docker-images/snapshot-builder.tar || true
        if: steps.cache-docker.outputs.cache-hit == 'true'
      - run: |
          docker build -t lyft/${{ secrets.package_name }}:${{ github.sha }} . --target builder --cache-from=flytepropeller-cache
          docker build -t lyft/${{ secrets.package_name }}:${{ github.sha }} .
      - run: docker tag lyft/${{ secrets.package_name }}:${{ github.sha }} ${{ secrets.package_name }}-cache && mkdir -p /tmp//tmp/docker-images && docker save flytepropeller-cache -o /tmp//tmp/docker-images/snapshot.tar && ls -lh /tmp//tmp/docker-images || true
        if: always() && steps.cache-docker.outputs.cache-hit != 'true'

